# Generated by Django 5.2.8 on 2025-11-25 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tempo_total_segundos', models.IntegerField()),
                ('status', models.CharField(choices=[('CONFIGURADO', 'Configurado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PAUSADO', 'Pausado'), ('ENCERRADO', 'Encerrado')], default='CONFIGURADO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo_nome', models.CharField(max_length=100)),
                ('participante_nome', models.CharField(max_length=100)),
                ('debate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debates.debate')),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('participante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='debates.participante')),
                ('tempo_acumulado_ms', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='participante_ativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debates_ativos', to='debates.participante'),
        ),
    ]
